export type Route = { method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'; path: string };

/** Every `/api` route registered in `back/internal/httpx/router.go` (except asynqmon HTML). */
export const GO_ROUTES: Route[] = [
	{ method: 'GET', path: '/api/auth/status' },
	{ method: 'POST', path: '/api/auth/login' },
	{ method: 'POST', path: '/api/auth/register' },
	{ method: 'POST', path: '/api/auth/oauth2/authorize' },
	{ method: 'POST', path: '/api/auth/oauth2/callback' },
	{ method: 'GET', path: '/api/auth/passkey/authentication/options' },
	{ method: 'POST', path: '/api/auth/passkey/authentication/verify' },

	{ method: 'GET', path: '/api/sub/:shortUuid/info' },
	{ method: 'GET', path: '/api/sub/:shortUuid/:clientType' },
	{ method: 'GET', path: '/api/sub/:shortUuid' },

	{ method: 'GET', path: '/api/users/tags' },
	{ method: 'GET', path: '/api/users/stream' },
	{ method: 'POST', path: '/api/users/resolve' },
	{ method: 'POST', path: '/api/users/bulk/delete-by-status' },
	{ method: 'POST', path: '/api/users/bulk/update' },
	{ method: 'POST', path: '/api/users/bulk/reset-traffic' },
	{ method: 'POST', path: '/api/users/bulk/revoke-subscription' },
	{ method: 'POST', path: '/api/users/bulk/delete' },
	{ method: 'POST', path: '/api/users/bulk/update-squads' },
	{ method: 'POST', path: '/api/users/bulk/extend-expiration-date' },
	{ method: 'POST', path: '/api/users/bulk/all/update' },
	{ method: 'POST', path: '/api/users/bulk/all/reset-traffic' },
	{ method: 'POST', path: '/api/users/bulk/all/extend-expiration-date' },
	{ method: 'GET', path: '/api/users/by-username/:username' },
	{ method: 'GET', path: '/api/users/by-short-uuid/:shortUuid' },
	{ method: 'GET', path: '/api/users/:userId/accessible-nodes' },
	{ method: 'GET', path: '/api/users/:userId/subscription-request-history' },
	{ method: 'POST', path: '/api/users/:userId/actions/enable' },
	{ method: 'POST', path: '/api/users/:userId/actions/disable' },
	{ method: 'POST', path: '/api/users/:userId/actions/reset-traffic' },
	{ method: 'POST', path: '/api/users/:userId/actions/revoke' },
	{ method: 'POST', path: '/api/users/:userId/actions/extend' },
	{ method: 'GET', path: '/api/users/:userId' },
	{ method: 'DELETE', path: '/api/users/:userId' },
	{ method: 'GET', path: '/api/users' },
	{ method: 'POST', path: '/api/users' },
	{ method: 'PATCH', path: '/api/users' },
	{ method: 'GET', path: '/api/keygen' },

	{ method: 'GET', path: '/api/nodes/tags' },
	{ method: 'POST', path: '/api/nodes/actions/restart-all' },
	{ method: 'POST', path: '/api/nodes/actions/reorder' },
	{ method: 'POST', path: '/api/nodes/bulk-actions/profile-modification' },
	{ method: 'POST', path: '/api/nodes/bulk-actions/update' },
	{ method: 'POST', path: '/api/nodes/bulk-actions' },
	{ method: 'POST', path: '/api/nodes/:uuid/actions/enable' },
	{ method: 'POST', path: '/api/nodes/:uuid/actions/disable' },
	{ method: 'POST', path: '/api/nodes/:uuid/actions/restart' },
	{ method: 'POST', path: '/api/nodes/:uuid/actions/reset-traffic' },
	{ method: 'GET', path: '/api/nodes/:uuid' },
	{ method: 'DELETE', path: '/api/nodes/:uuid' },
	{ method: 'GET', path: '/api/nodes' },
	{ method: 'POST', path: '/api/nodes' },
	{ method: 'PATCH', path: '/api/nodes' },

	{ method: 'GET', path: '/api/hosts/tags' },
	{ method: 'POST', path: '/api/hosts/actions/reorder' },
	{ method: 'POST', path: '/api/hosts/bulk/enable' },
	{ method: 'POST', path: '/api/hosts/bulk/disable' },
	{ method: 'POST', path: '/api/hosts/bulk/delete' },
	{ method: 'PATCH', path: '/api/hosts/bulk/update' },
	{ method: 'GET', path: '/api/hosts' },
	{ method: 'POST', path: '/api/hosts' },
	{ method: 'PATCH', path: '/api/hosts' },
	{ method: 'GET', path: '/api/hosts/:uuid' },
	{ method: 'DELETE', path: '/api/hosts/:uuid' },

	{ method: 'GET', path: '/api/config-profiles/inbounds' },
	{ method: 'POST', path: '/api/config-profiles/actions/reorder' },
	{ method: 'GET', path: '/api/config-profiles' },
	{ method: 'POST', path: '/api/config-profiles' },
	{ method: 'PATCH', path: '/api/config-profiles' },
	{ method: 'GET', path: '/api/config-profiles/:uuid/inbounds' },
	{ method: 'GET', path: '/api/config-profiles/:uuid/computed-config' },
	{ method: 'GET', path: '/api/config-profiles/:uuid' },
	{ method: 'DELETE', path: '/api/config-profiles/:uuid' },

	{ method: 'GET', path: '/api/snippets' },
	{ method: 'POST', path: '/api/snippets' },
	{ method: 'PATCH', path: '/api/snippets' },
	{ method: 'DELETE', path: '/api/snippets' },
	{ method: 'POST', path: '/api/snippets/actions/sync' },

	{ method: 'GET', path: '/api/remnawave-settings' },
	{ method: 'PATCH', path: '/api/remnawave-settings' },

	{ method: 'POST', path: '/api/internal-squads/actions/reorder' },
	{ method: 'GET', path: '/api/internal-squads' },
	{ method: 'POST', path: '/api/internal-squads' },
	{ method: 'PATCH', path: '/api/internal-squads' },
	{ method: 'GET', path: '/api/internal-squads/:uuid/accessible-nodes' },
	{ method: 'POST', path: '/api/internal-squads/:uuid/bulk-actions/add-users' },
	{ method: 'DELETE', path: '/api/internal-squads/:uuid/bulk-actions/remove-users' },
	{ method: 'GET', path: '/api/internal-squads/:uuid' },
	{ method: 'DELETE', path: '/api/internal-squads/:uuid' },

	{ method: 'POST', path: '/api/external-squads/actions/reorder' },
	{ method: 'GET', path: '/api/external-squads' },
	{ method: 'POST', path: '/api/external-squads' },
	{ method: 'PATCH', path: '/api/external-squads' },
	{ method: 'GET', path: '/api/external-squads/:uuid' },
	{ method: 'DELETE', path: '/api/external-squads/:uuid' },
	{ method: 'POST', path: '/api/external-squads/:uuid/bulk-actions/add-users' },
	{ method: 'DELETE', path: '/api/external-squads/:uuid/bulk-actions/remove-users' },

	{ method: 'GET', path: '/api/hwid/devices/stats' },
	{ method: 'GET', path: '/api/hwid/devices/top-users' },
	{ method: 'POST', path: '/api/hwid/devices/delete' },
	{ method: 'POST', path: '/api/hwid/devices/delete-all' },
	{ method: 'GET', path: '/api/hwid/devices' },
	{ method: 'POST', path: '/api/hwid/devices' },
	{ method: 'GET', path: '/api/hwid/devices/:userId' },

	{ method: 'GET', path: '/api/tokens/scopes' },
	{ method: 'GET', path: '/api/tokens/ott' },
	{ method: 'GET', path: '/api/tokens' },
	{ method: 'POST', path: '/api/tokens' },
	{ method: 'DELETE', path: '/api/tokens/:uuid' },

	{ method: 'GET', path: '/api/passkeys/registration/options' },
	{ method: 'POST', path: '/api/passkeys/registration/verify' },
	{ method: 'GET', path: '/api/passkeys' },
	{ method: 'DELETE', path: '/api/passkeys' },
	{ method: 'PATCH', path: '/api/passkeys' },

	{ method: 'GET', path: '/api/node-plugins/shared-lists' },
	{ method: 'POST', path: '/api/node-plugins/shared-lists' },
	{ method: 'PATCH', path: '/api/node-plugins/shared-lists' },
	{ method: 'GET', path: '/api/node-plugins/shared-lists/:name' },
	{ method: 'DELETE', path: '/api/node-plugins/shared-lists/:name' },
	{ method: 'POST', path: '/api/node-plugins/shared-lists/actions/sync' },
	{ method: 'GET', path: '/api/node-plugins/torrent-blocker/stats' },
	{ method: 'GET', path: '/api/node-plugins/torrent-blocker' },
	{ method: 'DELETE', path: '/api/node-plugins/torrent-blocker/truncate' },
	{ method: 'POST', path: '/api/node-plugins/actions/reorder' },
	{ method: 'POST', path: '/api/node-plugins/actions/clone' },
	{ method: 'POST', path: '/api/node-plugins/actions/sync' },
	{ method: 'POST', path: '/api/node-plugins/executor' },
	{ method: 'GET', path: '/api/node-plugins' },
	{ method: 'POST', path: '/api/node-plugins' },
	{ method: 'PATCH', path: '/api/node-plugins' },
	{ method: 'GET', path: '/api/node-plugins/:uuid' },
	{ method: 'DELETE', path: '/api/node-plugins/:uuid' },

	{ method: 'GET', path: '/api/metadata/user/:userId' },
	{ method: 'PUT', path: '/api/metadata/user/:userId' },
	{ method: 'GET', path: '/api/metadata/node/:uuid' },
	{ method: 'PUT', path: '/api/metadata/node/:uuid' },

	{ method: 'GET', path: '/api/subscription-request-history/stats' },
	{ method: 'GET', path: '/api/subscription-request-history' },

	{ method: 'POST', path: '/api/subscription-page-configs/actions/reorder' },
	{ method: 'POST', path: '/api/subscription-page-configs/actions/clone' },
	{ method: 'GET', path: '/api/subscription-page-configs' },
	{ method: 'POST', path: '/api/subscription-page-configs' },
	{ method: 'PATCH', path: '/api/subscription-page-configs' },
	{ method: 'GET', path: '/api/subscription-page-configs/:uuid' },
	{ method: 'DELETE', path: '/api/subscription-page-configs/:uuid' },

	{ method: 'POST', path: '/api/subscription-templates/actions/reorder' },
	{ method: 'GET', path: '/api/subscription-templates' },
	{ method: 'POST', path: '/api/subscription-templates' },
	{ method: 'PATCH', path: '/api/subscription-templates' },
	{ method: 'GET', path: '/api/subscription-templates/:uuid' },
	{ method: 'DELETE', path: '/api/subscription-templates/:uuid' },

	{ method: 'GET', path: '/api/subscription-settings' },
	{ method: 'PATCH', path: '/api/subscription-settings' },

	{ method: 'POST', path: '/api/connections/by-user/:userId' },
	{ method: 'GET', path: '/api/connections/by-user/:jobId' },
	{ method: 'POST', path: '/api/connections/by-node/:uuid' },
	{ method: 'GET', path: '/api/connections/by-node/:jobId' },
	{ method: 'POST', path: '/api/connections/geocheck/:uuid' },
	{ method: 'GET', path: '/api/connections/geocheck/:jobId' },
	{ method: 'POST', path: '/api/connections/drop' },

	{ method: 'GET', path: '/api/node-integrations' },
	{ method: 'POST', path: '/api/node-integrations' },
	{ method: 'PATCH', path: '/api/node-integrations' },
	{ method: 'GET', path: '/api/node-integrations/:uuid' },
	{ method: 'DELETE', path: '/api/node-integrations/:uuid' },

	{ method: 'GET', path: '/api/infra-billing/providers' },
	{ method: 'POST', path: '/api/infra-billing/providers' },
	{ method: 'PATCH', path: '/api/infra-billing/providers' },
	{ method: 'GET', path: '/api/infra-billing/providers/:uuid' },
	{ method: 'DELETE', path: '/api/infra-billing/providers/:uuid' },
	{ method: 'GET', path: '/api/infra-billing/nodes' },
	{ method: 'POST', path: '/api/infra-billing/nodes' },
	{ method: 'PATCH', path: '/api/infra-billing/nodes' },
	{ method: 'DELETE', path: '/api/infra-billing/nodes/:uuid' },
	{ method: 'GET', path: '/api/infra-billing/history' },
	{ method: 'POST', path: '/api/infra-billing/history' },
	{ method: 'DELETE', path: '/api/infra-billing/history/:uuid' },

	{ method: 'GET', path: '/api/system/stats/bandwidth' },
	{ method: 'GET', path: '/api/system/stats/nodes' },
	{ method: 'GET', path: '/api/system/stats/recap' },
	{ method: 'GET', path: '/api/system/stats/digest' },
	{ method: 'GET', path: '/api/system/stats/http' },
	{ method: 'GET', path: '/api/system/stats' },
	{ method: 'GET', path: '/api/system/nodes/metrics' },
	{ method: 'GET', path: '/api/system/tools/x25519/generate' },
	{ method: 'POST', path: '/api/system/testers/srr-matcher' },
	{ method: 'GET', path: '/api/system/health' },
	{ method: 'GET', path: '/api/system/metadata' },
	{ method: 'GET', path: '/api/system/configuration' },

	{ method: 'GET', path: '/api/bandwidth-stats/nodes/:uuid/users' },
	{ method: 'POST', path: '/api/bandwidth-stats/nodes/users' },
	{ method: 'POST', path: '/api/bandwidth-stats/nodes/usage' },
	{ method: 'GET', path: '/api/bandwidth-stats/nodes' },
	{ method: 'GET', path: '/api/bandwidth-stats/users/:userId' },
	{ method: 'GET', path: '/api/bandwidth-stats/internal-squads/:squadUuid/users/:userId/usage' },
	{ method: 'GET', path: '/api/bandwidth-stats/internal-squads/:uuid/usage' }
];
