export type Route = { method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'; path: string };

/** Every `/api` route registered across Arcanum microservices. */
export const GO_ROUTES: Route[] = [
	{ method: 'POST', path: '/api/auth/login' },
	{ method: 'POST', path: '/api/auth/switch-space' },

	{ method: 'GET', path: '/api/spaces' },
	{ method: 'POST', path: '/api/spaces' },
	{ method: 'GET', path: '/api/spaces/:spaceId' },
	{ method: 'GET', path: '/api/spaces/:spaceId/members' },
	{ method: 'POST', path: '/api/spaces/:spaceId/members' },
	{ method: 'PATCH', path: '/api/spaces/:spaceId/members/:userId' },
	{ method: 'DELETE', path: '/api/spaces/:spaceId/members/:userId' },
	{ method: 'GET', path: '/api/spaces/:spaceId/keys' },
	{ method: 'POST', path: '/api/spaces/:spaceId/keys' },

	{ method: 'GET', path: '/api/spaces/:spaceId/teams' },
	{ method: 'POST', path: '/api/spaces/:spaceId/teams' },
	{ method: 'GET', path: '/api/spaces/:spaceId/teams/:teamId' },
	{ method: 'PATCH', path: '/api/spaces/:spaceId/teams/:teamId' },
	{ method: 'POST', path: '/api/spaces/:spaceId/teams/:teamId/members' },

	{ method: 'GET', path: '/api/spaces/:spaceId/work/overview' },
	{ method: 'GET', path: '/api/spaces/:spaceId/issues' },
	{ method: 'POST', path: '/api/spaces/:spaceId/issues' },
	{ method: 'GET', path: '/api/spaces/:spaceId/issues/:issueId' },
	{ method: 'PATCH', path: '/api/spaces/:spaceId/issues/:issueId' },
	{ method: 'GET', path: '/api/spaces/:spaceId/issues/:issueId/activity' },
	{ method: 'POST', path: '/api/spaces/:spaceId/issues/:issueId/relations' },
	{ method: 'GET', path: '/api/spaces/:spaceId/issues/:issueId/comments' },
	{ method: 'POST', path: '/api/spaces/:spaceId/issues/:issueId/comments' },
	{ method: 'GET', path: '/api/spaces/:spaceId/labels' },
	{ method: 'POST', path: '/api/spaces/:spaceId/labels' },
	{ method: 'GET', path: '/api/spaces/:spaceId/work/cycles' },
	{ method: 'POST', path: '/api/spaces/:spaceId/work/cycles' },
	{ method: 'GET', path: '/api/spaces/:spaceId/work/projects' },
	{ method: 'POST', path: '/api/spaces/:spaceId/work/projects' },
	{ method: 'GET', path: '/api/spaces/:spaceId/work/views' },
	{ method: 'POST', path: '/api/spaces/:spaceId/work/views' },

	{ method: 'GET', path: '/api/spaces/:spaceId/agents/runs' },
	{ method: 'POST', path: '/api/spaces/:spaceId/agents/runs' },
	{ method: 'GET', path: '/api/spaces/:spaceId/agents/runs/:runId' },
	{ method: 'POST', path: '/api/spaces/:spaceId/agents/runs/:runId/cancel' },
	{ method: 'GET', path: '/api/spaces/:spaceId/agents/memory' },
	{ method: 'POST', path: '/api/spaces/:spaceId/agents/memory' },
	{ method: 'GET', path: '/api/spaces/:spaceId/agents/skills' },
	{ method: 'POST', path: '/api/spaces/:spaceId/agents/skills' },

	{ method: 'GET', path: '/api/spaces/:spaceId/channels' },
	{ method: 'POST', path: '/api/spaces/:spaceId/channels' },
	{ method: 'GET', path: '/api/spaces/:spaceId/channels/:channelId' },
	{ method: 'GET', path: '/api/spaces/:spaceId/channels/:channelId/messages' },
	{ method: 'POST', path: '/api/spaces/:spaceId/channels/:channelId/messages' },
	{ method: 'GET', path: '/api/spaces/:spaceId/channels/:channelId/messages/:messageId/reactions' },
	{ method: 'POST', path: '/api/spaces/:spaceId/channels/:channelId/messages/:messageId/reactions' },

	{ method: 'GET', path: '/api/spaces/:spaceId/integ/connectors' },
	{ method: 'POST', path: '/api/spaces/:spaceId/integ/connectors' },
	{ method: 'GET', path: '/api/spaces/:spaceId/integ/connectors/:connectorId' },
	{ method: 'PATCH', path: '/api/spaces/:spaceId/integ/connectors/:connectorId' },
	{ method: 'GET', path: '/api/spaces/:spaceId/integ/connectors/:connectorId/repos' },
	{ method: 'POST', path: '/api/spaces/:spaceId/integ/connectors/:connectorId/repos' },
	{ method: 'GET', path: '/api/spaces/:spaceId/integ/webhooks' },
	{ method: 'POST', path: '/api/spaces/:spaceId/integ/webhooks' },
	{ method: 'GET', path: '/api/spaces/:spaceId/integ/deliveries' },
	{ method: 'POST', path: '/api/integ/hooks/:connectorId' },
	{ method: 'POST', path: '/api/integ/hooks/github/:connectorId' },
	{ method: 'POST', path: '/api/integ/hooks/telegram/:connectorId' },

	{ method: 'GET', path: '/api/spaces/:spaceId/blobs' },
	{ method: 'POST', path: '/api/spaces/:spaceId/blobs' },
	{ method: 'GET', path: '/api/spaces/:spaceId/blobs/:blobId' },
	{ method: 'DELETE', path: '/api/spaces/:spaceId/blobs/:blobId' },
	{ method: 'GET', path: '/api/spaces/:spaceId/blobs/:blobId/url' },

	{ method: 'GET', path: '/api/spaces/:spaceId/machines' },
	{ method: 'POST', path: '/api/spaces/:spaceId/machines' },
	{ method: 'GET', path: '/api/spaces/:spaceId/machines/:machineId' },
	{ method: 'POST', path: '/api/spaces/:spaceId/machines/:machineId/stop' },
	{ method: 'POST', path: '/api/spaces/:spaceId/machines/:machineId/exec' },
	{ method: 'GET', path: '/api/spaces/:spaceId/machines/:machineId/proxy/:port' },

	{ method: 'GET', path: '/api/logs' }
];
